### ISSUE TITLE
opening project not always in sync with database

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#10]
When opening projects in which frames were previously deleted error "Can't load image from file.  File does not exist" displays.

**Comment by notklaatu** [comment]
This is a known issue, and in a way is related to my planned enhancement [Issue 6](https://github.com/notklaatu/stopgo/issues/6). Both issues boil down to the sqlite database used as a project file. 

Thinking about it, I'm not sure if the sqlite database really serves any purpose except while the application itself is open. Maybe we should just recreate a fresh DB each time we open a project. The real CPU burden is on scaling images for the timeline, which has nothing to do with the DB. The DB really just serves as place for sequence and as a kind of UNDO source. Once the user closes, the DB is basically redundant to the IMG DIR. Using the IMG DIR as the real source of a project gives us, magically, the ability to import any directory of images, granting us Issue 6. 

Two birds → one stone

**Comment by notklaatu** [comment]
fixed in c8481d7
