### ISSUE TITLE
AppImage should be called .AppImage

### ISSUE THREAD

**Issue by probonopd** [notklaatu/stopgo#12]
http://makerbox.org.nz/stopgo/ has download links for Linux.

AppImage should be called `.AppImage` rather than `.AppDir`. The AppImage is a container that has an AppDir inside; the AppDir is what you get when you unpack an AppImage.

**Comment by notklaatu** [comment]
fixed in Makefile
commit fa32acb

Need to produce 32 bit version and upload to Makerbox.org.nz, so not closing this issue yet

**Comment by notklaatu** [comment]
Actually I'm going to close this issue, because I'm not convinced I'm gonna bother with an official 32bit AppImage any time soon. When I do, I'll be using the same script as my 64bit AppImage, so the name will be correct.
