### ISSUE TITLE
Python Error Image Location

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#14]
Python error displaying "...unable to find image file X"
Clicking OK on error
Program has last frame captured selected and highlighted. Capture button not functioning, returns same error.

Unselecting frame and returning program to live view resulted in capture button running again, program then ran without issue. 
-A

**Comment by notklaatu** [comment]
thanks adam, thanks Makerbox Lego Animation beta testers at Scots College.

fixed in c8481d7
