### ISSUE TITLE
Thumbnail Select Highlight

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#17]
Make thumbnail select more noticeable with either a bright rectangle around the outside of the thumbnail or pick a more noticeable colour than the current black & white, perhaps MakerBox blue (#19B3B7)?

**Comment by notklaatu** [comment]
571edbc Merge branch 'timeliney' timeline improvements
2ac64c2 resizing select icon
f71a415 25% smaller bitmap for select icon
9fa2cca selected frame gets overlay icon
4105a07 select icon
23a7fc3 Upload Select Icon
fff84c6 larger thumbnails with slight scale effect when selected
