### ISSUE TITLE
gray button states

### ISSUE THREAD

**Issue by notklaatu** [notklaatu/stopgo#30]
If in play mode, gray-out capture button.

If in capture button, gray-out play button (?)

@cyanidecupcake is this correct, or should play button always be active?

**Comment by cyanidecupcake** [comment]
@notklaatu Kind of.

Play Mode -- gray-out capture button & delete button (once added)

Capture Mode -- nothing grayed out, you should be able to press play to enter play mode from capture mode.

**Comment by notklaatu** [comment]
9445f2d adjusting render
9b962ae buttons gray out during play and render
