### ISSUE TITLE
Render, No File

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#32]
Rendering appears to work.  Asks where you want to save the file, shows red bar at bottom, gives you a dialogue box when complete, however no file is actually created.

**Comment by notklaatu** [comment]
not an issue with stopgo, i just forgot to install deps on the class machines. mea culpa.

this does, however, uncover a related bug: if no ffmpeg -> then friendly error message rather than silent failure. Opening separate ticket for this.

[WONTFIX]
