### ISSUE TITLE
Update Broke Playback & Frame Deletion

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#48]
After the most recent update we are having issues with playback and the ability to delete frames.  This issue has turned up on three out of four computers so far.  One computer had issues from the start, the other two started displaying this issue after further use later in the same 1.5 hour class.

What is happening:
Clicking into the Timeline - No star on selected frame.  Camera icon grays out to indicate user is in playback mode, but the play button doesn't trigger playback.   

Deletion - If a frame is selected for deletion, no star on frame and pressing delete/backspace button has no result.

**Comment by notklaatu** [comment]
Fixed in latest (until proven otherwise)
