### ISSUE TITLE
Exception when running on Arch Linux 

### ISSUE THREAD

**Issue by phunni** [notklaatu/stopgo#50]
When I attempt to run the Linux 64 bit AppImage file on 64 bit Arch Linux I get the following error message:

 ```
File "./bin//stopgo", line 55
    except Exception, err:
                    ^
SyntaxError: invalid syntax
```

I have both vlc and ffmpeg installed

**Comment by notklaatu** [comment]
If I had to guess, it's a Python3-related error. I'll look into it during next sprint.

Thanks for the bug report! I appreciate it!

**Comment by notklaatu** [comment]
AppImage has changed its structure.  So far I've been unable to produce a functional AppImage, so going with a traditional install for now. Will revisit AppImage in the future after getting familiar with the new version.
