### ISSUE TITLE
Timeline Stops Repainting

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#9]
Timeline stops repainting after an unknown number of frames.  Users cannot scroll to see frames past a certain point.  Resizing the window fixes the problem.

evt_repaint

**Comment by notklaatu** [comment]
Possibly we need to force a periodic repaint. It's supposed to be repainting itself after each CAPTURE but some condition must be skipping this. I wonder if it's related to people deleting a frame. Either way, I'll look into it after S+ART

**Comment by notklaatu** [comment]
Fixed in latest (until proven otherwise)
